### ISSUE TITLE
can i test in revit 2018

### ISSUE THREAD

**Issue by johnfelipe** [jeremytammik/CustomExporterCollada#1]
Is possible teach me how integrate to revit 2018
Stay alert

**Comment by jeremytammik** [comment]
i just performed a flat migration to Revit 2018 for you, cf. release 2018.0.0.0. for all further information on integrating a Revit add-in, please refer to the getting started material at http://thebuildingcoder.typepad.com/blog/about-the-author.html#2

**Comment by johnfelipe** [comment]
i havent visual studio, and i only want test export my revit model to second life collada viewer, with textures included, is possible share me installable?

**Comment by jeremytammik** [comment]
dear john felipe, this is sample source code for programmers. if you are not a programmer yourself, please ask a friend who is. a good place to talk with other Revit API programmers is the Revit API discussion forum: https://forums.autodesk.com/t5/revit-api-forum/bd-p/160. certainly somebody there will be able to help you.

**Comment by johnfelipe** [comment]
Then this haven't bin or executable files?

**Comment by jeremytammik** [comment]
this repository contains source code only. you can compile it as an add-in using the Visual Studio project included. you can also copy the code into a C# macro and run it using the built-in SharpDevelop IDE.
