### ISSUE TITLE
Merging Faces

### ISSUE THREAD

**Issue by SIBIMMS** [jeremytammik/CustomExporterCollada#2]
Greetings,
First i would like to congratulate you for your efforts on creating this Revit Exporter.
I have been messing around with it and i am able to export the model geometry, but the problem is that it comes way to split. For example a simple cup (from the rac_basic_sample_project) is exported in 16 different pieces, making the model way to heavy to be viewed in a game engine like unity.
I managed to pinpoint a common ground between all the pieces (all the pieces have the same Unique ID) but i am still unable to create a unique object/mesh composed by all the faces (in a optimized way that would let me reduce the model complexity).
Do you have any tip that you could give me on how this could be accomplished?
Thanks for your attention and sorry if this is not the best place for me to ask you for advices.

**Comment by jeremytammik** [comment]
thank you for your appreciation. unfortunately, there is not much i can do about this. this sample just implements the Revit API custom exporter interface and adds very little additional intelligence to that. what you are asking for would require more intelligence than this sample is designed for. i am afraid you will have to tackle this task yourself. you have two options: use the custom exporter and piece the parts together yourself, or do not use the custom exporter. the Revit API offers other methods to access element geometry. some of them may give you the geometry in one piece like you require.

**Comment by SIBIMMS** [comment]
Greetings,
First i would like thank you for your reply.
About those methods, I have been trying to find them but i wasn't able to do so. Do you know, by head, any of them, so i could study them?
Thank you very much.

**Comment by jeremytammik** [comment]
Basically, the other methods involve retrieving the element geometry from each element one by one using the Element.Geometry property (get_Geometry method in C#):

https://apidocs.co/apps/revit/2019/d8a55a5b-2a69-d5ab-3e1f-6cf1ee43c8ec.htm
